/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISettlementToken,
  ISettlementTokenInterface,
} from "../../../../../contracts/domain/interfaces/Settlement/ISettlementToken";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "string",
        name: "status",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "burned",
        type: "bool",
      },
    ],
    name: "AuthorizationStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
    ],
    name: "SettlementTokenBurned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "date",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "participantType",
        type: "string",
      },
    ],
    name: "SettlementTokenMinted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
    ],
    name: "mintSettlementToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISettlementToken__factory {
  static readonly abi = _abi;
  static createInterface(): ISettlementTokenInterface {
    return new Interface(_abi) as ISettlementTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISettlementToken {
    return new Contract(address, _abi, runner) as unknown as ISettlementToken;
  }
}
