/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuthorizationTokenFactory,
  IAuthorizationTokenFactoryInterface,
} from "../../../../../contracts/base/Factory/interfaces/IAuthorizationTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "participantWallet",
        type: "address",
      },
      {
        internalType: "address",
        name: "trackerAddress",
        type: "address",
      },
    ],
    name: "createAuthorizationToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAuthorizationTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthorizationTokenFactoryInterface {
    return new Interface(_abi) as IAuthorizationTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuthorizationTokenFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAuthorizationTokenFactory;
  }
}
