/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISettlementTokenFactory,
  ISettlementTokenFactoryInterface,
} from "../../../../../contracts/base/Factory/interfaces/ISettlementTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "participantWallet",
        type: "address",
      },
      {
        internalType: "address",
        name: "trackerAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "authorizationTokenAddress",
        type: "address",
      },
    ],
    name: "createSettlementToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISettlementTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ISettlementTokenFactoryInterface {
    return new Interface(_abi) as ISettlementTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISettlementTokenFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISettlementTokenFactory;
  }
}
