/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenBase,
  ITokenBaseInterface,
} from "../../../../../contracts/domain/interfaces/TokenBase/ITokenBase";

const _abi = [
  {
    inputs: [],
    name: "getAllNridsGeneratedByThisContract",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenBase__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenBaseInterface {
    return new Interface(_abi) as ITokenBaseInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITokenBase {
    return new Contract(address, _abi, runner) as unknown as ITokenBase;
  }
}
