/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as application from "./application";
export type { application };
import type * as base from "./base";
export type { base };
import type * as domain from "./domain";
export type { domain };
