/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ManagementCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ManagementCore__factory>;
    getContractFactory(
      name: "ManagementStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ManagementStorage__factory>;
    getContractFactory(
      name: "TransactionTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransactionTracker__factory>;
    getContractFactory(
      name: "AuthorizationToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuthorizationToken__factory>;
    getContractFactory(
      name: "AuthorizationTokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuthorizationTokenFactory__factory>;
    getContractFactory(
      name: "IAuthorizationTokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuthorizationTokenFactory__factory>;
    getContractFactory(
      name: "ISettlementTokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISettlementTokenFactory__factory>;
    getContractFactory(
      name: "SettlementTokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SettlementTokenFactory__factory>;
    getContractFactory(
      name: "SettlementToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SettlementToken__factory>;
    getContractFactory(
      name: "TokenBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenBase__factory>;
    getContractFactory(
      name: "IAuthorizationToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuthorizationToken__factory>;
    getContractFactory(
      name: "IAuthorizationTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAuthorizationTracker__factory>;
    getContractFactory(
      name: "ITransactionTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITransactionTracker__factory>;
    getContractFactory(
      name: "IManagementCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IManagementCore__factory>;
    getContractFactory(
      name: "ISettlementToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISettlementToken__factory>;
    getContractFactory(
      name: "ISettlementTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISettlementTracker__factory>;
    getContractFactory(
      name: "ITokenBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITokenBase__factory>;
    getContractFactory(
      name: "ERC721A__IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721A__factory>;
    getContractFactory(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721A__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ManagementCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ManagementCore>;
    getContractAt(
      name: "ManagementStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ManagementStorage>;
    getContractAt(
      name: "TransactionTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransactionTracker>;
    getContractAt(
      name: "AuthorizationToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AuthorizationToken>;
    getContractAt(
      name: "AuthorizationTokenFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AuthorizationTokenFactory>;
    getContractAt(
      name: "IAuthorizationTokenFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuthorizationTokenFactory>;
    getContractAt(
      name: "ISettlementTokenFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISettlementTokenFactory>;
    getContractAt(
      name: "SettlementTokenFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SettlementTokenFactory>;
    getContractAt(
      name: "SettlementToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SettlementToken>;
    getContractAt(
      name: "TokenBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenBase>;
    getContractAt(
      name: "IAuthorizationToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuthorizationToken>;
    getContractAt(
      name: "IAuthorizationTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAuthorizationTracker>;
    getContractAt(
      name: "ITransactionTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITransactionTracker>;
    getContractAt(
      name: "IManagementCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IManagementCore>;
    getContractAt(
      name: "ISettlementToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISettlementToken>;
    getContractAt(
      name: "ISettlementTracker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISettlementTracker>;
    getContractAt(
      name: "ITokenBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITokenBase>;
    getContractAt(
      name: "ERC721A__IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A__IERC721Receiver>;
    getContractAt(
      name: "ERC721A",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721A>;
    getContractAt(
      name: "IERC721A",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721A>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ManagementCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManagementCore>;
    deployContract(
      name: "ManagementStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManagementStorage>;
    deployContract(
      name: "TransactionTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransactionTracker>;
    deployContract(
      name: "AuthorizationToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuthorizationToken>;
    deployContract(
      name: "AuthorizationTokenFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuthorizationTokenFactory>;
    deployContract(
      name: "IAuthorizationTokenFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationTokenFactory>;
    deployContract(
      name: "ISettlementTokenFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementTokenFactory>;
    deployContract(
      name: "SettlementTokenFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementTokenFactory>;
    deployContract(
      name: "SettlementToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementToken>;
    deployContract(
      name: "TokenBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenBase>;
    deployContract(
      name: "IAuthorizationToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationToken>;
    deployContract(
      name: "IAuthorizationTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationTracker>;
    deployContract(
      name: "ITransactionTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransactionTracker>;
    deployContract(
      name: "IManagementCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IManagementCore>;
    deployContract(
      name: "ISettlementToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementToken>;
    deployContract(
      name: "ISettlementTracker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementTracker>;
    deployContract(
      name: "ITokenBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenBase>;
    deployContract(
      name: "ERC721A__IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721A__IERC721Receiver>;
    deployContract(
      name: "ERC721A",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721A>;
    deployContract(
      name: "IERC721A",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721A>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ManagementCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManagementCore>;
    deployContract(
      name: "ManagementStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ManagementStorage>;
    deployContract(
      name: "TransactionTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransactionTracker>;
    deployContract(
      name: "AuthorizationToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuthorizationToken>;
    deployContract(
      name: "AuthorizationTokenFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuthorizationTokenFactory>;
    deployContract(
      name: "IAuthorizationTokenFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationTokenFactory>;
    deployContract(
      name: "ISettlementTokenFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementTokenFactory>;
    deployContract(
      name: "SettlementTokenFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementTokenFactory>;
    deployContract(
      name: "SettlementToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementToken>;
    deployContract(
      name: "TokenBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenBase>;
    deployContract(
      name: "IAuthorizationToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationToken>;
    deployContract(
      name: "IAuthorizationTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAuthorizationTracker>;
    deployContract(
      name: "ITransactionTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransactionTracker>;
    deployContract(
      name: "IManagementCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IManagementCore>;
    deployContract(
      name: "ISettlementToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementToken>;
    deployContract(
      name: "ISettlementTracker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISettlementTracker>;
    deployContract(
      name: "ITokenBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITokenBase>;
    deployContract(
      name: "ERC721A__IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721A__IERC721Receiver>;
    deployContract(
      name: "ERC721A",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721A>;
    deployContract(
      name: "IERC721A",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721A>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
