/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuthorizationTracker,
  IAuthorizationTrackerInterface,
} from "../../../../../contracts/domain/interfaces/Authorization/IAuthorizationTracker";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
    ],
    name: "getAuthorizationInfo",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAuthorizationTracker__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthorizationTrackerInterface {
    return new Interface(_abi) as IAuthorizationTrackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuthorizationTracker {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAuthorizationTracker;
  }
}
