/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITransactionTracker,
  ITransactionTrackerInterface,
} from "../../../../contracts/domain/interfaces/ITransactionTracker";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nrid",
        type: "uint256",
      },
    ],
    name: "getTransactionInfo",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "participantWallet",
        type: "address",
      },
    ],
    name: "getTransactionsByParticipant",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum ITransactionTracker.TransactionStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "getTransactionsByStatus",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITransactionTracker__factory {
  static readonly abi = _abi;
  static createInterface(): ITransactionTrackerInterface {
    return new Interface(_abi) as ITransactionTrackerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITransactionTracker {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITransactionTracker;
  }
}
