/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ManagementCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addParticipant"
      | "getParticipantInfo"
      | "getTransactionInfo"
      | "getTransactionsByParticipant"
      | "getTransactionsByStatus"
      | "managementStorage"
      | "owner"
      | "renounceOwnership"
      | "setAuthorizationTokenFactoryAddress"
      | "setSettlementTokenFactoryAddress"
      | "transactionTracker"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "ParticipantAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addParticipant",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionsByParticipant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "managementStorage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizationTokenFactoryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettlementTokenFactoryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactionTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionsByParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managementStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizationTokenFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSettlementTokenFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactionTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantAddedEvent {
  export type InputTuple = [
    participantWallet: AddressLike,
    participantType: string
  ];
  export type OutputTuple = [
    participantWallet: string,
    participantType: string
  ];
  export interface OutputObject {
    participantWallet: string;
    participantType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ManagementCore extends BaseContract {
  connect(runner?: ContractRunner | null): ManagementCore;
  waitForDeployment(): Promise<this>;

  interface: ManagementCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addParticipant: TypedContractMethod<
    [participantWallet: AddressLike, participantName: string],
    [void],
    "nonpayable"
  >;

  getParticipantInfo: TypedContractMethod<
    [participantAddress: AddressLike],
    [string],
    "view"
  >;

  getTransactionInfo: TypedContractMethod<
    [nrid: BigNumberish],
    [string],
    "view"
  >;

  getTransactionsByParticipant: TypedContractMethod<
    [participantWallet: AddressLike],
    [string[]],
    "view"
  >;

  getTransactionsByStatus: TypedContractMethod<
    [status: BigNumberish],
    [string[]],
    "view"
  >;

  managementStorage: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizationTokenFactoryAddress: TypedContractMethod<
    [_authorizationTokenFactoryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setSettlementTokenFactoryAddress: TypedContractMethod<
    [_settlementTokenFactoryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transactionTracker: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addParticipant"
  ): TypedContractMethod<
    [participantWallet: AddressLike, participantName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getParticipantInfo"
  ): TypedContractMethod<[participantAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTransactionInfo"
  ): TypedContractMethod<[nrid: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTransactionsByParticipant"
  ): TypedContractMethod<[participantWallet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransactionsByStatus"
  ): TypedContractMethod<[status: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "managementStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizationTokenFactoryAddress"
  ): TypedContractMethod<
    [_authorizationTokenFactoryAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettlementTokenFactoryAddress"
  ): TypedContractMethod<
    [_settlementTokenFactoryAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactionTracker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantAdded"
  ): TypedContractEvent<
    ParticipantAddedEvent.InputTuple,
    ParticipantAddedEvent.OutputTuple,
    ParticipantAddedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParticipantAdded(address,string)": TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;
    ParticipantAdded: TypedContractEvent<
      ParticipantAddedEvent.InputTuple,
      ParticipantAddedEvent.OutputTuple,
      ParticipantAddedEvent.OutputObject
    >;
  };
}
