/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AuthorizationTokenFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createAuthorizationToken"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AuthorizationTokenCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createAuthorizationToken",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAuthorizationToken",
    data: BytesLike
  ): Result;
}

export namespace AuthorizationTokenCreatedEvent {
  export type InputTuple = [
    participantWallet: AddressLike,
    authorizationTokenAddress: AddressLike
  ];
  export type OutputTuple = [
    participantWallet: string,
    authorizationTokenAddress: string
  ];
  export interface OutputObject {
    participantWallet: string;
    authorizationTokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuthorizationTokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): AuthorizationTokenFactory;
  waitForDeployment(): Promise<this>;

  interface: AuthorizationTokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAuthorizationToken: TypedContractMethod<
    [participantWallet: AddressLike, trackerAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAuthorizationToken"
  ): TypedContractMethod<
    [participantWallet: AddressLike, trackerAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorizationTokenCreated"
  ): TypedContractEvent<
    AuthorizationTokenCreatedEvent.InputTuple,
    AuthorizationTokenCreatedEvent.OutputTuple,
    AuthorizationTokenCreatedEvent.OutputObject
  >;

  filters: {
    "AuthorizationTokenCreated(address,address)": TypedContractEvent<
      AuthorizationTokenCreatedEvent.InputTuple,
      AuthorizationTokenCreatedEvent.OutputTuple,
      AuthorizationTokenCreatedEvent.OutputObject
    >;
    AuthorizationTokenCreated: TypedContractEvent<
      AuthorizationTokenCreatedEvent.InputTuple,
      AuthorizationTokenCreatedEvent.OutputTuple,
      AuthorizationTokenCreatedEvent.OutputObject
    >;
  };
}
