/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SettlementTokenFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createSettlementToken"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SettlementTokenCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createSettlementToken",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSettlementToken",
    data: BytesLike
  ): Result;
}

export namespace SettlementTokenCreatedEvent {
  export type InputTuple = [
    participantWallet: AddressLike,
    settlementTokenAddress: AddressLike
  ];
  export type OutputTuple = [
    participantWallet: string,
    settlementTokenAddress: string
  ];
  export interface OutputObject {
    participantWallet: string;
    settlementTokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementTokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementTokenFactory;
  waitForDeployment(): Promise<this>;

  interface: SettlementTokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSettlementToken: TypedContractMethod<
    [
      participantWallet: AddressLike,
      trackerAddress: AddressLike,
      authorizationTokenAddress: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSettlementToken"
  ): TypedContractMethod<
    [
      participantWallet: AddressLike,
      trackerAddress: AddressLike,
      authorizationTokenAddress: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "SettlementTokenCreated"
  ): TypedContractEvent<
    SettlementTokenCreatedEvent.InputTuple,
    SettlementTokenCreatedEvent.OutputTuple,
    SettlementTokenCreatedEvent.OutputObject
  >;

  filters: {
    "SettlementTokenCreated(address,address)": TypedContractEvent<
      SettlementTokenCreatedEvent.InputTuple,
      SettlementTokenCreatedEvent.OutputTuple,
      SettlementTokenCreatedEvent.OutputObject
    >;
    SettlementTokenCreated: TypedContractEvent<
      SettlementTokenCreatedEvent.InputTuple,
      SettlementTokenCreatedEvent.OutputTuple,
      SettlementTokenCreatedEvent.OutputObject
    >;
  };
}
